# Generated by Django 3.2.5 on 2024-01-31 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('depot_code', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(help_text='0=active;1=inactive;2=delete')),
            ],
        ),
        migrations.CreateModel(
            name='OperationType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(help_text='0=active;1=inactive;2=delete')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('phone_number', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(help_text='0=active;1=inactive;2=delete')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depot', to='app.depot')),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(help_text='0=active;1=inactive;2=delete')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(help_text='0=active;1=inactive;2=delete')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_created_user', to='app.user')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_updated_user', to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bus_number', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(help_text='0=active;1=inactive;2=delete')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_details_created_user', to='app.user')),
                ('depot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_details_depot', to='app.depot')),
                ('opt_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_details_opt_type', to='app.operationtype')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_details_updated_user', to='app.user')),
                ('vehicle_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_details_vehicle', to='app.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_type', to='app.usertype'),
        ),
        migrations.CreateModel(
            name='SpecialBusDataEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('log_sheet_no', models.CharField(max_length=256)),
                ('driver1_name', models.CharField(max_length=256)),
                ('drive1_staff_name', models.CharField(max_length=256)),
                ('driver1_phone_number', models.CharField(max_length=256)),
                ('driver2_name', models.CharField(max_length=256)),
                ('drive2_staff_name', models.CharField(max_length=256)),
                ('drive2_phone_number', models.CharField(max_length=256)),
                ('incharge_name', models.CharField(max_length=256)),
                ('incharge_phone_number', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(help_text='0=active;1=inactive;2=delete')),
                ('bus_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_bus_vehicle', to='app.vehicle')),
                ('bus_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_bus_opt_type', to='app.operationtype')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_bus_created_user', to='app.user')),
                ('special_bus_reporting_depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_bus_reporting_depot', to='app.depot')),
                ('special_bus_sending_depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_bus_sending_depot', to='app.depot')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_bus_updated_user', to='app.user')),
            ],
        ),
        migrations.AddField(
            model_name='operationtype',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opt_type_created_user', to='app.user'),
        ),
        migrations.AddField(
            model_name='operationtype',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opt_type_updated_user', to='app.user'),
        ),
    ]
