# Generated by Django 3.2.5 on 2024-01-31 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depot',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depot_created_user', to='app.user'),
        ),
        migrations.AddField(
            model_name='depot',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depot_updated_user', to='app.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='depot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.depot'),
        ),
    ]
