# Generated by Django 3.2.5 on 2024-01-31 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20240131_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_type_created_user', to='app.user'),
        ),
        migrations.AddField(
            model_name='usertype',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_type_updated_user', to='app.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.usertype'),
        ),
    ]
