# Generated by Django 3.2.5 on 2024-02-01 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20240131_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='updated_by',
        ),
    ]
