# Generated by Django 3.2.5 on 2024-02-01 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20240201_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depot',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='depot',
            name='updated_by',
        ),
    ]
