# Generated by Django 3.2.5 on 2024-02-01 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20240201_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='depot',
            name='created_by',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depot_created_user', to='app.user'),
        ),
        migrations.AddField(
            model_name='depot',
            name='updated_by',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depot_updated_user', to='app.user'),
        ),
        migrations.AddField(
            model_name='usertype',
            name='created_by',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_type_created_user', to='app.user'),
        ),
        migrations.AddField(
            model_name='usertype',
            name='updated_by',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_type_updated_user', to='app.user'),
        ),
        migrations.AlterField(
            model_name='operationtype',
            name='created_by',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opt_type_created_user', to='app.user'),
        ),
        migrations.AlterField(
            model_name='operationtype',
            name='updated_by',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opt_type_updated_user', to='app.user'),
        ),
        migrations.AlterField(
            model_name='specialbusdataentry',
            name='created_by',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_bus_created_user', to='app.user'),
        ),
        migrations.AlterField(
            model_name='specialbusdataentry',
            name='updated_by',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_bus_updated_user', to='app.user'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='created_by',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_created_user', to='app.user'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='updated_by',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_updated_user', to='app.user'),
        ),
        migrations.AlterField(
            model_name='vehicledetails',
            name='created_by',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_details_created_user', to='app.user'),
        ),
        migrations.AlterField(
            model_name='vehicledetails',
            name='updated_by',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_details_updated_user', to='app.user'),
        ),
    ]
