# Generated by Django 3.2.5 on 2024-02-01 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20240201_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicledetails',
            old_name='depot_id',
            new_name='depot',
        ),
    ]
