# Generated by Django 3.2.5 on 2024-02-01 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20240201_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialbusdataentry',
            name='bus_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_bus_vehicle', to='app.vehicledetails'),
        ),
    ]
