# Generated by Django 3.2.5 on 2024-02-01 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_specialbusdataentry_bus_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialbusdataentry',
            old_name='drive1_staff_name',
            new_name='drive1_staff_no',
        ),
        migrations.RenameField(
            model_name='specialbusdataentry',
            old_name='drive2_staff_name',
            new_name='drive2_staff_no',
        ),
    ]
