# Generated by Django 3.2.5 on 2024-02-01 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20240201_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialbusdataentry',
            old_name='drive1_staff_no',
            new_name='driver1_staff_no',
        ),
        migrations.RenameField(
            model_name='specialbusdataentry',
            old_name='drive2_phone_number',
            new_name='driver2_phone_number',
        ),
        migrations.RenameField(
            model_name='specialbusdataentry',
            old_name='drive2_staff_no',
            new_name='driver2_staff_no',
        ),
    ]
