# Generated by Django 3.2.5 on 2024-02-02 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20240202_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depot',
            name='depot_code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='depot',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='operationtype',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='operationtype',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='specialbusdataentry',
            name='driver1_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='specialbusdataentry',
            name='driver1_phone_number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='specialbusdataentry',
            name='driver1_staff_no',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='specialbusdataentry',
            name='driver2_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='specialbusdataentry',
            name='driver2_phone_number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='specialbusdataentry',
            name='driver2_staff_no',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='specialbusdataentry',
            name='incharge_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='specialbusdataentry',
            name='incharge_phone_number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='specialbusdataentry',
            name='log_sheet_no',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='vehicledetails',
            name='bus_number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='vehicledetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicledetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='StatisticsDateEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bus_unique_code', models.CharField(blank=True, max_length=256, null=True)),
                ('total_ticket_amount', models.CharField(blank=True, max_length=256, null=True)),
                ('total_adult_passengers', models.CharField(blank=True, max_length=256, null=True)),
                ('total_child_passengers', models.CharField(blank=True, max_length=256, null=True)),
                ('mhl_adult_passengers', models.CharField(blank=True, max_length=256, null=True)),
                ('mhl_child_passengers', models.CharField(blank=True, max_length=256, null=True)),
                ('mhl_adult_amount', models.CharField(blank=True, max_length=256, null=True)),
                ('mhl_child_amount', models.CharField(blank=True, max_length=256, null=True)),
                ('entry_type', models.CharField(blank=True, max_length=256, null=True)),
                ('service_operated_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(help_text='0=active;1=inactive;2=delete')),
                ('created_by', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics_data_entry_created_user', to='app.user')),
                ('updated_by', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics_data_entry_updated_user', to='app.user')),
            ],
        ),
    ]
