# Generated by Django 3.2.5 on 2024-02-02 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20240202_1539'),
        ('app', '0012_outdepotvehiclereceive'),
    ]

    operations = [
    ]
