# Generated by Django 3.2.5 on 2024-02-02 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20240202_2340'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OwnDepotWithdrawMedaramOperation',
            new_name='OwnDepotBusWithdraw',
        ),
    ]
