# Generated by Django 3.2.5 on 2024-02-02 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_owndepotwithdrawmedaramoperation_owndepotbuswithdraw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owndepotbuswithdraw',
            name='created_by',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='own_depot_bus_withdraw_created_user', to='app.user'),
        ),
        migrations.AlterField(
            model_name='owndepotbuswithdraw',
            name='updated_by',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='own_depot_bus_withdraw_updated_user', to='app.user'),
        ),
    ]
