# Generated by Django 3.2.5 on 2024-02-03 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_hsdoilsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusesOnHand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_name', models.CharField(blank=True, max_length=256, null=True)),
                ('unique_code', models.CharField(blank=True, max_length=256, null=True)),
                ('bus_in_out', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(blank=True, help_text='0=active;1=inactive;2=delete', null=True)),
                ('created_by', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buses_on_hand_created_user', to='app.user')),
                ('special_bus_data_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses_on_hand_special_bus', to='app.specialbusdataentry')),
                ('updated_by', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buses_on_hand_updated_user', to='app.user')),
            ],
        ),
    ]
