# Generated by Django 3.2.5 on 2024-02-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_busesonhand'),
    ]

    operations = [
        migrations.AddField(
            model_name='depot',
            name='bus_allotted_buses',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
