# Generated by Django 3.2.5 on 2024-02-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_rename_bus_allotted_buses_depot_buses_allotted'),
    ]

    operations = [
        migrations.AddField(
            model_name='outdepotvehiclereceive',
            name='out_depot_bus_reporting_depot',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='outdepotvehiclereceive',
            name='out_depot_bus_sending_depot',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
