# Generated by Django 3.2.5 on 2024-02-04 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20240204_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outdepotvehiclereceive',
            name='out_depot_bus_reporting_depot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='out_depot_bus_reporting_depot', to='app.depot'),
        ),
        migrations.AlterField(
            model_name='outdepotvehiclereceive',
            name='out_depot_bus_sending_depot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='out_depot_bus_sending_depot', to='app.depot'),
        ),
    ]
