# Generated by Django 3.2.5 on 2024-02-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20240204_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depot',
            name='buses_allotted',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
