# Generated by Django 3.2.5 on 2024-02-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_depot_buses_allotted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depot',
            name='buses_allotted',
            field=models.IntegerField(default=0),
        ),
    ]
