# Generated by Django 3.2.5 on 2024-02-06 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_depot_buses_allotted'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_name', models.CharField(blank=True, max_length=256, null=True)),
                ('status', models.IntegerField(blank=True, help_text='0=active;1=inactive;2=delete', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='point_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_point_data', to='app.pointdata'),
        ),
    ]
