# Generated by Django 3.2.5 on 2024-02-06 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20240206_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busesonhand',
            name='point_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buses_on_hand_point_data', to='app.pointdata'),
        ),
    ]
