# Generated by Django 3.2.5 on 2024-02-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_busesonhand_point_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outdepotvehiclesentback',
            old_name='unique_no_bus_no',
            new_name='unique_no',
        ),
        migrations.AddField(
            model_name='outdepotvehiclesentback',
            name='bus_number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
