# Generated by Django 3.2.5 on 2024-02-06 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20240206_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripStatistics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unique_code', models.IntegerField(blank=True, null=True)),
                ('bus_number', models.CharField(blank=True, max_length=256, null=True)),
                ('total_ticket_amount', models.CharField(blank=True, max_length=256, null=True)),
                ('total_adult_passengers', models.CharField(blank=True, max_length=256, null=True)),
                ('total_child_passengers', models.CharField(blank=True, max_length=256, null=True)),
                ('mhl_adult_passengers', models.CharField(blank=True, max_length=256, null=True)),
                ('mhl_child_passengers', models.CharField(blank=True, max_length=256, null=True)),
                ('mhl_adult_amount', models.CharField(blank=True, max_length=256, null=True)),
                ('mhl_child_amount', models.CharField(blank=True, max_length=256, null=True)),
                ('entry_type', models.CharField(blank=True, max_length=256, null=True)),
                ('service_operated_date', models.DateField(blank=True, null=True)),
                ('trip_start', models.DateTimeField(auto_now_add=True)),
                ('trip_verified', models.BooleanField(default=False)),
                ('trip_verified_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(help_text='0=active;1=inactive;2=delete')),
                ('created_by', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics_data_entry_created_user', to='app.user')),
                ('data_enter_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics_data_entry_by', to='app.user')),
                ('data_verify_by', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics_data_verify_by', to='app.user')),
            ],
        ),
        migrations.AddField(
            model_name='pointdata',
            name='depot_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.depot'),
        ),
        migrations.AddField(
            model_name='pointdata',
            name='region',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='pointdata',
            name='zone',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.DeleteModel(
            name='StatisticsDateEntry',
        ),
        migrations.AddField(
            model_name='tripstatistics',
            name='point_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistic_date_entry_point_data', to='app.pointdata'),
        ),
        migrations.AddField(
            model_name='tripstatistics',
            name='updated_by',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics_data_entry_updated_user', to='app.user'),
        ),
    ]
