# Generated by Django 3.2.5 on 2024-02-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20240206_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='hsdoilsubmission',
            name='shift',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
