# Generated by Django 3.2.5 on 2024-02-06 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_hsdoilsubmission_shift'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripstatistics',
            old_name='data_verify_by',
            new_name='trip_verify_by',
        ),
    ]
