# Generated by Django 3.2.5 on 2024-02-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_rename_data_verify_by_tripstatistics_trip_verify_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripstatistics',
            name='trip_verified_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
