# Generated by Django 3.2.5 on 2024-02-07 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_tripstatistics_trip_verified_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripstatistics',
            name='point_name',
        ),
        migrations.AddField(
            model_name='tripstatistics',
            name='start_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistic_start_from_point_data', to='app.pointdata'),
        ),
        migrations.AddField(
            model_name='tripstatistics',
            name='start_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistic_start_to_point_data', to='app.pointdata'),
        ),
    ]
