# Generated by Django 3.2.5 on 2024-02-07 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20240207_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripstatistics',
            name='start_from',
        ),
        migrations.RemoveField(
            model_name='tripstatistics',
            name='start_to',
        ),
        migrations.AddField(
            model_name='tripstatistics',
            name='start_form_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistic_start_from_location_point_data', to='app.pointdata'),
        ),
        migrations.AddField(
            model_name='tripstatistics',
            name='start_to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistic_start_to_location_point_data', to='app.pointdata'),
        ),
    ]
