# Generated by Django 3.2.5 on 2024-02-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20240207_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripstatistics',
            name='trip_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
