# Generated by Django 3.2.5 on 2024-02-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_tripstatistics_trip_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='employee_designation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
