# Generated by Django 3.2.5 on 2024-02-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_usertype_employee_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripstatistics',
            name='mhl_adult_amount',
            field=models.IntegerField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='tripstatistics',
            name='mhl_adult_passengers',
            field=models.IntegerField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='tripstatistics',
            name='mhl_child_amount',
            field=models.IntegerField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='tripstatistics',
            name='mhl_child_passengers',
            field=models.IntegerField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='tripstatistics',
            name='total_adult_passengers',
            field=models.IntegerField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='tripstatistics',
            name='total_child_passengers',
            field=models.IntegerField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='tripstatistics',
            name='total_ticket_amount',
            field=models.IntegerField(blank=True, max_length=256, null=True),
        ),
    ]
