# Generated by Django 3.2.5 on 2024-02-08 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20240208_2348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripstatistics',
            old_name='start_form_location',
            new_name='start_from_location',
        ),
    ]
