# Generated by Django 3.2.5 on 2024-02-09 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_rename_start_form_location_tripstatistics_start_from_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='owndepotbusdetailsentry',
            name='depot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.depot'),
        ),
        migrations.AddField(
            model_name='owndepotbuswithdraw',
            name='depot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.depot'),
        ),
    ]
