# Generated by Django 3.2.5 on 2024-02-12 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20240209_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owndepotbusdetailsentry',
            name='bus_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='own_depot_bus_detail_vehicle_details', to='app.vehicledetails'),
        ),
    ]
