# Generated by Django 3.2.5 on 2024-02-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_alter_owndepotbusdetailsentry_bus_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripstatistics',
            name='trip_verified_time',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
    ]
