# Generated by Django 3.2.5 on 2024-02-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_alter_tripstatistics_trip_verified_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripstatistics',
            name='trip_verified_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
