# Generated by Django 3.2.5 on 2024-02-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_alter_tripstatistics_trip_verified_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='owndepotbusdetailsentry',
            name='driver1_staff_no',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='owndepotbusdetailsentry',
            name='driver2_staff_no',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='owndepotbusdetailsentry',
            name='incharge_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='owndepotbusdetailsentry',
            name='incharge_phone_number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
